// AUTHORIZATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// LIBRARIES
export const FETCH_LIBRARIES = 'FETCH_LIBRARIES';
export const EDIT_LIBRARY = 'EDIT_LIBRARY';

// HEADMASTER
export const FETCH_HEADMASTER_SCHOOLS = 'FETCH_HEADMASTER_SCHOOLS';
export const FETCH_HEADMASTER_SCHOOL = 'FETCH_HEADMASTER_SCHOOL';
export const FETCH_HEADMASTER_PROFILE = 'FETCH_HEADMASTER_PROFILE';
export const FETCH_HEADMASTER_PROFILE_SUCCESS =
  'FETCH_HEADMASTER_PROFILE_SUCCESS';
export const FETCH_HEADMASTER_PROFILE_FAILURE =
  'FETCH_HEADMASTER_PROFILE_FAILURE';

// VILLAGES
export const FETCH_VILLAGE = 'FETCH_VILLAGE';
export const EDIT_VILLAGE = 'EDIT_VILLAGE';

// MENTEES
export const FETCH_MENTEE_START = 'FETCH_MENTEE_START';
export const FETCH_MENTEE_SUCCESS = 'FETCH_MENTEE_SUCCESS';
export const FETCH_MENTEE_FAILURE = 'FETCH_MENTEE_FAILURE';

export const EDIT_MENTEE_START = 'EDIT_MENTEE_START';
export const EDIT_MENTEE_SUCCESS = 'EDIT_MENTEE_SUCCESS';
export const EDIT_MENTEE_FAILURE = 'EDIT_MENTEE_FAILURE';


// Teacher Actions
export const FETCH_TEACHER_PROFILE = 'FETCH_TEACHER_PROFILE';

